apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StackitMachine
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-stackit
    app.kubernetes.io/managed-by: kustomize
  name: stackitmachine-sample
spec:
  machineType: g1.2
  imageId: "00000000-0000-0000-0000-000000000000"
